[Feat/auth] argument resolver 마무리
DDD-Community/DDD-10-WABLE-SERVER pull request #19
Opened 2024-02-22 16:14 UTC by Minsoo-Shin

PULL_REQUEST_TEMPLATE.md

## 내용
* argument resolver 로 token 확인하여 Users 데이터 생성
* 모든 controller 인풋 파라미터에 Users 추가

Close #이슈번호

2024-02-23 13:49 UTC, aihoshistar commented on src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
> +        String token = authorization.replaceAll("^Bearer( )*", "");
```java
 String authorization = httpServletRequest.getHeader("Authorization");
```
authorization 가 Null 인 경우 replaceAll 을 진행할 수 없어 NullPointerException 에러가 발생합니다.

2024-02-23 14:02 UTC, aihoshistar commented on src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
>          String authorization = httpServletRequest.getHeader("Authorization");
핸들링을 잘 하기 위해 try/catch 으로 감싸는건 어떨까요? 
```java
        try {
            HttpServletRequest httpServletRequest = (HttpServletRequest) webRequest.getNativeRequest();
            String authorization = httpServletRequest.getHeader("Authorization");
            if (authorization == null) {
                throw new Error("token is empty");
            }

            String idToken = authorization.split(" ")[1];
            boolean hasToken = idToken == null;
            if (hasToken) {
                throw new Error("token is invalid");
            }

            boolean verify = VerifyToken.verify(idToken);
            if (!verify) {
                throw new Error("token is disprove");
            }

            String username = AwsCognitoJwtParserUtil.getClaim(idToken, "cognito:username");
            return Users.builder()
                    .userId(username)
                    .build(); // Users 객체를 빌드
        } catch (Exception e) {
            throw new UnauthorizedException(e.getMessage());
        }
```

2024-02-23 14:04 UTC, aihoshistar commented on src/main/java/com/wable/harmonika/domain/group/GroupService.java
>          List<Groups> groups = userGroups.stream()
```
        List<UserGroups> userGroups = userGroupRepository.findAllByUser(new Users( null)); // todo userId
      --      --      --      --      --      --      --      --      --      --      --      --      --      --      --  > 여기 공백도 지워주시면 좋을것같습니다 
```

2024-02-23 14:12 UTC, aihoshistar commented on src/main/java/com/wable/harmonika/domain/card/service/impl/CardServiceImpl.java
Controller 의 역할에 맞게 Cards.Builder() 의 관심사를 분리하는 것도 좋을 것 같습니다 

```
..
Cards card = buildCard(cardsRequest, fromUser);
..

```

```java
    private Cards buildCard(CardsRequest cardsRequest, Users fromUser) {
        // Cards 객체 빌드
        return new Cards.Builder()
                .sid(cardsRequest.getSid())
                .content(cardsRequest.getContent())
                .isVisible(cardsRequest.isVisible())
                .build();
```

2024-02-23 14:14 UTC, aihoshistar commented
고생하셨습니다 

다른건 괜찮은데 `NullPointerException` 가 발생하는 [UserArgumentResolver.java](https://github.com/DDD-Community/DDD-10-WABLE-SERVER/pull/19/files/57a56d0b356153eb438720dd78ceb52b675ad1ee#diff-167db293936e36e3f7b19953a6c050f5d1c5d49fc699f3a020b09b221ab61d1b)  부분만 수정 부탁드립니다 

감사합니다

2024-02-23 14:17 UTC, aihoshistar requested changes
고생하셨습니다 

다른건 괜찮은데 `NullPointerException` 가 발생하는 [UserArgumentResolver.java](https://github.com/DDD-Community/DDD-10-WABLE-SERVER/pull/19/files/57a56d0b356153eb438720dd78ceb52b675ad1ee#diff-167db293936e36e3f7b19953a6c050f5d1c5d49fc699f3a020b09b221ab61d1b)  부분만 수정 부탁드립니다 

감사합니다

2024-02-23 14:24 UTC, aihoshistar commented on src/main/java/com/wable/harmonika/domain/card/api/CardController.java
>      }
매개변수의 순서데로 어노테이션이라고 하나 저걸..  그게 실행되기 때문에 Users user 을 가장 앞에 두시는건 어떠하십니까 
```
public void updateCards(@Valid UpdateCardsRequest request, Users user) throws Exception {
    Cards cards =  cardService.update();
}
```

2024-02-24 01:56 UTC, Minsoo-Shin commented on src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
>          String authorization = httpServletRequest.getHeader("Authorization");
예외 상황이 있을 수 있으니 감싸놓는게 좋겠네요

2024-02-24 01:57 UTC, Minsoo-Shin commented on src/main/java/com/wable/harmonika/domain/card/service/impl/CardServiceImpl.java
이건 테스트 용이라 지울게요!

2024-02-24 05:34 UTC, Minsoo-Shin commented on src/main/java/com/wable/harmonika/domain/card/service/impl/CardServiceImpl.java
여기 service layer 입니다

2024-02-24 05:36 UTC, aihoshistar approved these changes

2024-02-24 07:00 UTC, aihoshistar commented on src/main/java/com/wable/harmonika/domain/card/service/impl/CardServiceImpl.java
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-02-24 07:47 UTC, merged